"""
Guardrail Agent for Parle-G Supply Chain Engine.
================================================
This module is Agent #4 (the final agent) in the Agentic AI Supply Chain Engine for Parle-G.
It implements Human-in-the-Loop (HITL) governance by evaluating the size of proposed
inter-warehouse stock transfers generated by Agent #3 (Rebalancing Agent).

System Architecture Context:
----------------------------
1. Order Intake Agent      -> Assigns priority scores (Government > NGO > Loyal > Regular).
2. Spatial Routing Agent   -> Aligns orders to regional warehouses; flags stock shortages.
3. Rebalancing Agent       -> Creates inter-warehouse stock transfer proposals.
4. Guardrail Agent (This)  -> Evaluates transfer sizes against approval thresholds and gates execution.

Guardrail Business Logic (Exact Rules):
---------------------------------------
Rule 1: Input Acceptance
        - Accepts a list of transfer request dictionaries.
        - Each transfer contains: transfer_id, from_warehouse, to_warehouse, sku, quantity, status.

Rule 2: Single Threshold Size Comparison (50,000 Units)
        - If quantity < 50,000 units:
            * Set status to "auto_approved" immediately.
            * The transfer is autonomous and does not require manager intervention.
        - If quantity >= 50,000 units:
            * Set status to "pending_manager_approval".
            * The transfer is halted and gated until a human manager explicitly signs off.
            * CRITICAL: Exactly 50,000 units requires manager approval (it is NOT auto-approved).

Rule 3: Deterministic & Rule-Based
        - Pure deterministic arithmetic comparison (no AI model, LLM call, or external API needed).

Rule 4: Human-in-the-Loop Approval Action
        - Function approve_transfer(transfer_id, transfers_list) allows a manager
          (e.g., via a future dashboard button) to manually change a "pending_manager_approval"
          transfer to "manager_approved".

Viva Voce / Technical Interview Notes:
--------------------------------------
Q: Why is the threshold set at 50,000 units?
A: In FMCG supply chain operations (like Parle-G), transfers under 50,000 units fit within
   standard regional redistribution capacity and carry low financial risk. Transfers of
   50,000+ units represent multi-truckload logistics, significant freight expenditure, and
   substantial capital movement, requiring operational sign-off.

Q: Why does EXACTLY 50,000 units require manager approval instead of auto-approval?
A: In risk management and security compliance, automated systems must adopt a "fail-safe /
   conservative boundary" policy. 50,000 represents the ceiling of automated autonomy.
   Therefore, 49,999 units is the highest allowable auto-approved transfer. At 50,000 units,
   the transfer touches the upper limit and authority must escalate to human governance.

Q: How does this simulate Human-in-the-Loop (HITL)?
A: Autonomous agents propose actions, but high-impact decisions are gated. The separate
   approve_transfer() function simulates the asynchronous callback triggered when an authorized
   human reviews and accepts the proposal on a dashboard.
"""

import logging
from typing import Any, Dict, List, Optional

# Set up dedicated logger for the guardrail agent
logger = logging.getLogger("guardrail_agent")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter("[%(levelname)s] %(name)s: %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

# Guardrail Status Constants
STATUS_AUTO_APPROVED = "auto_approved"
STATUS_PENDING_APPROVAL = "pending_manager_approval"
STATUS_MANAGER_APPROVED = "manager_approved"

# Guardrail Approval Threshold
# Transfers strictly below this limit are auto-approved;
# Transfers at or above this limit require manager approval.
APPROVAL_THRESHOLD_QUANTITY = 50000


def evaluate_transfers(
    transfers: List[Dict[str, Any]],
    threshold: int = APPROVAL_THRESHOLD_QUANTITY,
) -> List[Dict[str, Any]]:
    """
    Applies guardrail size checks to a list of transfer requests.

    Parameters:
    -----------
    transfers : List[Dict[str, Any]]
        List of transfer dictionaries generated by the Rebalancing Agent.
        Each dictionary contains:
        - transfer_id (str)
        - from_warehouse (str)
        - to_warehouse (str)
        - sku (str)
        - quantity (int)
        - status (str)
    threshold : int
        The upper quantity threshold for automatic approval (default: 50,000).

    Returns:
    --------
    List[Dict[str, Any]]
        The list of transfer dictionaries with their 'status' field updated:
        - 'auto_approved' if quantity < 50,000
        - 'pending_manager_approval' if quantity >= 50,000
    """
    if not transfers:
        logger.info("No transfer requests provided to Guardrail Agent.")
        return []

    for transfer in transfers:
        transfer_id = transfer.get("transfer_id", "Unknown")
        quantity = transfer.get("quantity", 0)

        # Rule 2: Check quantity against threshold
        # If quantity < 50,000 units: auto_approved immediately
        if quantity < threshold:
            transfer["status"] = STATUS_AUTO_APPROVED
            logger.info(
                f"Transfer '{transfer_id}': Quantity {quantity:,} < {threshold:,}. "
                f"Status set to '{STATUS_AUTO_APPROVED}'."
            )
        # If quantity >= 50,000 units (inclusive of 50,000): pending_manager_approval
        else:
            transfer["status"] = STATUS_PENDING_APPROVAL
            logger.warning(
                f"Transfer '{transfer_id}': Quantity {quantity:,} >= {threshold:,}. "
                f"Status set to '{STATUS_PENDING_APPROVAL}' (Manager approval required)."
            )

    return transfers


# Semantic alias
apply_guardrails = evaluate_transfers


def approve_transfer(
    transfer_id: str,
    transfers_list: List[Dict[str, Any]],
) -> bool:
    """
    Manually approves a transfer that is in 'pending_manager_approval' status.
    Simulates a human-in-the-loop action triggered by a manager (e.g., via a dashboard button).

    Parameters:
    -----------
    transfer_id : str
        The unique identifier of the transfer request to approve (e.g., 'TR-0003').
    transfers_list : List[Dict[str, Any]]
        The list of transfer request dictionaries containing the transfer.

    Returns:
    --------
    bool
        True if the transfer was found and its status was changed to 'manager_approved'.
        False if the transfer was not found or was not in 'pending_manager_approval' status.
    """
    for transfer in transfers_list:
        if transfer.get("transfer_id") == transfer_id:
            current_status = transfer.get("status")

            # Only transfers currently pending manager approval can be approved
            if current_status == STATUS_PENDING_APPROVAL:
                transfer["status"] = STATUS_MANAGER_APPROVED
                logger.info(
                    f"Transfer '{transfer_id}' approved by manager. "
                    f"Status: '{current_status}' -> '{STATUS_MANAGER_APPROVED}'."
                )
                return True
            else:
                logger.warning(
                    f"Transfer '{transfer_id}' cannot be approved: current status is "
                    f"'{current_status}', expected '{STATUS_PENDING_APPROVAL}'."
                )
                return False

    logger.warning(f"Transfer '{transfer_id}' not found in the provided transfers list.")
    return False


def print_guardrail_summary(transfers: List[Dict[str, Any]]) -> None:
    """
    Prints a clear, beginner-friendly summary table of evaluated transfer requests.
    Suitable for demonstrations and viva presentations.
    """
    print("\n" + "=" * 108)
    print("              PARLE-G AGENTIC AI SUPPLY CHAIN ENGINE: GUARDRAIL AGENT")
    print("=" * 108)
    header = (
        f"{'#':<3} | {'Transfer ID':<12} | {'From WH':<14} | {'To WH':<14} | "
        f"{'SKU':<14} | {'Quantity':<10} | {'Guardrail Status':<26}"
    )
    print(header)
    print("-" * 108)

    if not transfers:
        print("  No transfer requests to display.")
    else:
        for idx, tr in enumerate(transfers, start=1):
            tr_id = str(tr.get("transfer_id", "N/A"))
            from_wh = str(tr.get("from_warehouse", "N/A"))
            to_wh = str(tr.get("to_warehouse", "N/A"))
            sku = str(tr.get("sku", "N/A"))
            qty = f"{tr.get('quantity', 0):,}"
            status = str(tr.get("status", "N/A"))

            row = (
                f"{idx:<3} | {tr_id:<12} | {from_wh:<14} | {to_wh:<14} | "
                f"{sku:<14} | {qty:<10} | {status:<26}"
            )
            print(row)

    print("=" * 108)
    print("Guardrail Policy Rules:")
    print(" - Quantity < 50,000 units  : 'auto_approved'            (Autonomous transfer execution)")
    print(" - Quantity >= 50,000 units : 'pending_manager_approval' (Human-in-the-loop sign-off required)")
    print(" - Boundary check           : Exactly 50,000 units is flagged as 'pending_manager_approval'")
    print(" - After manual approval    : 'manager_approved'         (Manager sign-off recorded)")
    print("=" * 108 + "\n")


def demo_guardrail() -> List[Dict[str, Any]]:
    """
    Self-contained demonstration for manual execution, testing, and viva evaluation.
    Constructs sample transfers representing all key boundary conditions:
    1. Small transfer (1,500 units) -> auto_approved
    2. Boundary just under (49,999 units) -> auto_approved
    3. Boundary exactly at (50,000 units) -> pending_manager_approval
    4. Large transfer (75,000 units) -> pending_manager_approval
    5. Simulates Human-in-the-Loop manager approval on the 50,000 unit transfer.
    """
    print("\n>>> Running Self-Contained Parle-G Guardrail Agent Demo...")

    # Sample Transfers from Rebalancing Agent
    mock_transfers = [
        {
            "transfer_id": "TR-0001",
            "from_warehouse": "WH-WEST-01",
            "to_warehouse": "WH-NORTH-01",
            "sku": "PARLE-G-250G",
            "quantity": 1500,
            "status": "created",
        },
        {
            "transfer_id": "TR-0002",
            "from_warehouse": "WH-WEST-01",
            "to_warehouse": "WH-NORTH-01",
            "sku": "PARLE-G-100G",
            "quantity": 49999,  # Just under 50,000 -> auto_approved
            "status": "created",
        },
        {
            "transfer_id": "TR-0003",
            "from_warehouse": "WH-WEST-01",
            "to_warehouse": "WH-SOUTH-01",
            "sku": "PARLE-G-800G",
            "quantity": 50000,  # Exactly 50,000 -> pending_manager_approval
            "status": "created",
        },
        {
            "transfer_id": "TR-0004",
            "from_warehouse": "WH-NORTH-01",
            "to_warehouse": "WH-WEST-01",
            "sku": "PARLE-G-250G",
            "quantity": 75000,  # Over 50,000 -> pending_manager_approval
            "status": "created",
        },
    ]

    # Step 1: Apply guardrail evaluation
    print("\n[Step 1] Evaluating Transfer Requests against 50,000 Unit Threshold:")
    evaluated_transfers = evaluate_transfers(mock_transfers)
    print_guardrail_summary(evaluated_transfers)

    # Step 2: Simulate Human-in-the-Loop Manager Approval on TR-0003
    print("[Step 2] Simulating Human-in-the-Loop Manager Approval for TR-0003:")
    success = approve_transfer("TR-0003", evaluated_transfers)
    print(f"Approval Result for TR-0003: {'SUCCESS' if success else 'FAILED'}")

    # Step 3: Print updated summary showing manager approval
    print("\n[Step 3] Updated Transfers Table After Manager Sign-Off:")
    print_guardrail_summary(evaluated_transfers)

    return evaluated_transfers


if __name__ == "__main__":
    demo_guardrail()
